name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg;
          Pkg.add("CompatHelper");
          Pkg.Registry.add(RegistrySpec(url = "https://github.com/JuliaRegistries/General.git"));
          Pkg.Registry.add(RegistrySpec(url = "https://github.com/peterahrens/Peter.jl.git"))'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
